import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[window]
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 80
lines = 20

[font]
size = 14

[font.normal]
family = "MonaspiceAr NF"
style = "Regular"

[font.bold]
family = "MonaspiceAr NF"
style = "Bold" 

[font.italic]
family = "MonaspiceAr NF"
style = "Italic"

