import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[window.dimensions]
columns = 80
lines = 20

[font]
size = 10

[font.normal]
family = "MonaspiceArNerdFontMono"
style = "Medium"

[font.bold]
family = "MonaspiceArNerdFontMono"
style = "Bold" 

[font.italic]
family = "MonaspiceArNerdFontMono"
style = "Italic"

