format = """$time\
$directory\
$git_branch\
$git_state\
\n\
$character\
"""

[directory]
truncation_length = 10
truncate_to_repo = false
format = '[\[$path\]]($style)'
style = 'cyan'

[git_branch]
format = '[\[$symbol$branch(:$remote_branch)\]]($style)'
symbol = ''
style = 'purple'

[cmd_duration]
format = "[$duration]($style)"

[git_state]
style = 'yellow'

[character]
success_symbol = '[ ➜](green)'
error_symbol = '[ ✗](#E84D44) '

[time]
format = '[\[$time\]]($style)'
disabled = false
time_format = '%T'
style = 'yellow'
